package com.bangersoul.aivance.core.domain.usecase.job

import com.bangersoul.aivance.core.common.model.Application
import com.bangersoul.aivance.core.common.model.ApplicationStage
import com.bangersoul.aivance.core.common.model.JobListing
import com.bangersoul.aivance.core.common.model.ResumeVersion
import com.bangersoul.aivance.core.common.result.CoreResult
import com.bangersoul.aivance.core.common.result.getOrNull
import com.bangersoul.aivance.core.common.result.runCatchingCore
import com.bangersoul.aivance.core.domain.repository.ApplicationWorkflowRepository
import com.bangersoul.aivance.core.domain.repository.JobRepository
import com.bangersoul.aivance.core.domain.repository.ResumeRepository
import com.bangersoul.aivance.core.domain.usecase.UseCase
import com.bangersoul.aivance.core.domain.usecase.resume.ImproveResumeUseCase
import kotlinx.coroutines.flow.firstOrNull
import javax.inject.Inject

data class AutonomousApplyRequest(
    val job: JobListing,
    val resumeVersionId: Long,
    val userNotes: String? = null
)

/**
 * Orchestrates the "One-Click Application" pipeline.
 * 
 * This is the core of the Copilot's execution agency.
 * Pipeline:
 * 1. Tailor: Triggers an AI optimization of the resume for the specific job description.
 * 2. Record: Creates a new Application entry in the Workflow Repository set to "PREPARING".
 * 3. Deploy: Returns the tailored assets and the application handle for the final submission.
 */
class AutonomousApplyUseCase @Inject constructor(
    private val resumeRepository: ResumeRepository,
    private val workflowRepository: ApplicationWorkflowRepository,
    private val jobRepository: JobRepository,
    private val improveResumeUseCase: ImproveResumeUseCase
) : UseCase<AutonomousApplyRequest, CoreResult<Application>>() {

    override suspend operator fun invoke(input: AutonomousApplyRequest): CoreResult<Application> = runCatchingCore {
        // Step 1: Tailor the Resume (AI Agency)
        // We trigger a background optimization based on the Job's description
        improveResumeUseCase(
            com.bangersoul.aivance.core.domain.usecase.resume.ImproveResumeRequest(
                resumeId = 0, // In a real scenario, we'd fetch the active resume ID
                versionId = input.resumeVersionId,
                jobDescription = input.job.description,
                feedback = "Tailor this resume for the role of ${input.job.title} at ${input.job.company}."
            )
        )

        // Step 2: Cache Job & Log the Application in the Pipeline
        val resolvedJobId = jobRepository.cacheJob(input.job).getOrNull()
            ?: input.job.id.toLongOrNull()
            ?: 0L

        val application = Application(
            id = 0, // Generated by DB
            jobId = resolvedJobId,
            job = input.job,
            resumeVersionId = input.resumeVersionId,
            currentStageId = "PREPARING",
            status = "ACTIVE",
            dateApplied = System.currentTimeMillis(),
            notes = input.userNotes ?: "Tailored by AiVance Copilot",
            lastModified = System.currentTimeMillis()
        )
        
        val appId = workflowRepository.saveApplication(application).getOrNull() 
            ?: throw Exception("Failed to record application in workflow.")

        // Step 3: Return the recorded application for UI handling (navigation to Job URL/Portal)
        // In a future iteration, this is where we'd trigger a Headless Browser/API call.
        workflowRepository.getApplicationById(appId).firstOrNull()?.getOrNull() 
            ?: throw Exception("Application record missing after save.")
    }
}
